-- sql/cleanup.sql
-- Cleanup script for Frost Markets Intelligence Demo

-- WARNING: This will remove ALL demo data and components
-- Use with caution!

-- Drop search services first (they depend on tables)
USE DATABASE MARKETS_AI_DEMO;
USE SCHEMA AI;

DROP CORTEX SEARCH SERVICE IF EXISTS EARNINGS_TRANSCRIPTS_SEARCH;
DROP CORTEX SEARCH SERVICE IF EXISTS RESEARCH_REPORTS_SEARCH;
DROP CORTEX SEARCH SERVICE IF EXISTS NEWS_ARTICLES_SEARCH;

-- Drop semantic views
DROP VIEW IF EXISTS EARNINGS_ANALYSIS_VIEW;
DROP VIEW IF EXISTS PORTFOLIO_EXPOSURE_VIEW;
DROP VIEW IF EXISTS CLIENT_MARKET_IMPACT_VIEW;
DROP VIEW IF EXISTS THEMATIC_RESEARCH_VIEW;

-- Drop all schemas (this will drop all tables)
DROP SCHEMA IF EXISTS AI CASCADE;
DROP SCHEMA IF EXISTS CURATED CASCADE;
DROP SCHEMA IF EXISTS RAW CASCADE;

-- Drop warehouses
DROP WAREHOUSE IF EXISTS MARKETS_AI_DEMO_COMPUTE_WH;
DROP WAREHOUSE IF EXISTS MARKETS_AI_DEMO_SEARCH_WH;

-- Drop database (final cleanup)
DROP DATABASE IF EXISTS MARKETS_AI_DEMO CASCADE;

-- Confirmation message
SELECT 'Frost Markets Intelligence Demo environment cleaned up successfully' AS STATUS;
